version: 'latest'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka:
    image: apache/kafka
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPIC: "test_topic:1:3"